# Generated by Django 2.2 on 2019-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='kiwi.jpg', upload_to='profile_pictures/'),
        ),
    ]
