# Generated by Django 2.2 on 2019-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0002_auto_20190415_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(null=True, upload_to='cvs/'),
        ),
    ]
