# Generated by Django 2.2 on 2019-05-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0007_auto_20190512_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='account_type',
        ),
    ]
