# Generated by Django 2.2 on 2019-05-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0008_auto_20190512_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
    ]
