# Generated by Django 2.2 on 2019-04-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0002_auto_20190404_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOffert',
            new_name='Offert',
        ),
    ]
