# Generated by Django 2.2 on 2019-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0003_auto_20190405_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
    ]
