# Generated by Django 2.2 on 2019-04-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0005_auto_20190411_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('weppage', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Localisation',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='salary',
        ),
        migrations.AddField(
            model_name='company',
            name='webpage',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offert',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offert',
            name='per_hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offert',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='offert',
            name='must_have',
        ),
        migrations.AlterField(
            model_name='offert',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerts.Company'),
        ),
        migrations.AddField(
            model_name='offert',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offerts.Agency'),
        ),
        migrations.AddField(
            model_name='offert',
            name='must_have',
            field=models.ManyToManyField(to='offerts.Tag'),
        ),
    ]
