# Generated by Django 2.2 on 2019-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0007_auto_20190411_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
