# Generated by Django 2.2 on 2019-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0009_auto_20190411_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='logos/'),
        ),
    ]
