# Generated by Django 2.2 on 2019-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0012_auto_20190415_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='per_hour',
            field=models.BooleanField(default=False, verbose_name='Salary: per hour'),
        ),
    ]
