# Generated by Django 2.1.7 on 2019-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0013_auto_20190416_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='salary_type',
            field=models.CharField(choices=[('M', 'per hour'), ('H', 'monthly')], default='M', max_length=1),
        ),
    ]
