# Generated by Django 2.1.7 on 2019-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0014_offert_salary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offert',
            name='per_hour',
        ),
        migrations.AlterField(
            model_name='offert',
            name='salary_type',
            field=models.CharField(choices=[('H: ', 'per hour'), ('M', 'monthly')], default='M', max_length=1),
        ),
    ]
