# Generated by Django 2.1.7 on 2019-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0015_auto_20190511_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='salary_type',
            field=models.CharField(choices=[('H', 'per hour'), ('M', 'monthly')], default='M', max_length=1),
        ),
    ]
