# Generated by Django 2.2 on 2019-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0018_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(null=True, upload_to='cvs/'),
        ),
    ]
