# Generated by Django 2.1.7 on 2019-05-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0019_application_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=500)),
                ('answer_type', models.CharField(choices=[('T', 'text'), ('R', 'radio'), ('C', 'checkbox')], default='T', max_length=1)),
                ('answer_choices', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customapplication',
            name='custom_fields',
            field=models.ManyToManyField(to='offerts.CustomField'),
        ),
        migrations.AddField(
            model_name='customapplication',
            name='offert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerts.Offert'),
        ),
    ]
