# Generated by Django 2.2 on 2019-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0020_auto_20190520_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer_type', models.CharField(choices=[('T', 'text'), ('R', 'radio'), ('C', 'checkbox')], default='T', max_length=1)),
                ('answer_choices', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.AlterField(
            model_name='customapplication',
            name='custom_fields',
            field=models.ManyToManyField(to='offerts.CustomQuestion'),
        ),
    ]
