# Generated by Django 2.2 on 2019-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0021_auto_20190521_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='answer_type',
            field=models.CharField(choices=[('T', 'text'), ('R', 'radio'), ('C', 'checkbox')], default='T', max_length=1, null=True),
        ),
    ]
