# Generated by Django 2.2 on 2019-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0022_auto_20190521_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='answer_type',
            field=models.CharField(choices=[('T', 'text answer'), ('R', 'single-choice'), ('C', 'multiple-choice')], default='T', max_length=1, null=True),
        ),
    ]
