# Generated by Django 2.2 on 2019-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0023_auto_20190523_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='answer_type',
            field=models.CharField(choices=[('T', 'text'), ('R', 'single-choice'), ('C', 'multiple-choice')], default='T', max_length=1, null=True),
        ),
    ]
