# Generated by Django 2.2 on 2019-05-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0024_auto_20190523_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='offert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offerts.Offert'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomApplication',
        ),
    ]
