# Generated by Django 2.2 on 2019-05-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0026_remove_customquestion_offert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='offert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offerts.Offert'),
            preserve_default=False,
        ),
    ]
