# Generated by Django 2.2 on 2019-05-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0027_customquestion_offert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='offert',
        ),
    ]
