# Generated by Django 2.2 on 2019-05-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0029_customquestion_offert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomQuestion',
        ),
    ]
