# Generated by Django 2.2 on 2019-05-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0030_delete_customquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer_type', models.CharField(choices=[('T', 'text'), ('R', 'single-choice'), ('C', 'multiple-choice')], default='T', max_length=1, null=True)),
                ('answer_choices', models.TextField(null=True)),
                ('offert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offerts.Offert')),
            ],
        ),
    ]
