# Generated by Django 2.2 on 2019-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0032_auto_20190523_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(default=None, null=True, upload_to='cvs/'),
        ),
    ]
