# Generated by Django 2.2 on 2019-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerts', '0035_customanswer_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='max_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offert',
            name='min_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
