# Generated by Django 2.2 on 2019-04-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offerts', '0008_auto_20190411_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(null=True)),
                ('offert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerts.Offert')),
            ],
        ),
    ]
